### ISSUE TITLE
NowPlaying Music Screen

### ISSUE THREAD

**Issue by ShiraYuuki** [TsukiLite/TsukiMusicPlayer#1]
Make a basic music player for a specific directory. Play the music file from that directory and display info onto the screen.

**Comment by kymotsujason** [comment]
Nearly completed, just need QA and a look over.
https://github.com/TsukiLite/TsukiMusicPlayer/commit/8cd6e779b58e3266167e4459148225d5e3567a94

**Comment by ShiraYuuki** [comment]
Finish implementing basic music player window and application
 - WIP: buggy gesture detection
- WIP: Song Access File System
